[tams]
ntrajectories = 50
nsplititer = 2000
loglevel = "WARNING"

[trajectory]
end_time = 10.0
step_size = 0.01
targetscore = 0.95

[model]
epsilon = 0.1

[runner]
type = "asyncio"
nworker_init=2
nworker_iter=2
