[tams]
ntrajectories = 32
nsplititer = 1000
loglevel = "WARNING"

[trajectory]
end_time = 20.0
step_size = 0.01
targetscore = 1.05

[model]
inv_temperature = 5.67

[runner]
type = "asyncio"
nworker_init=1
nworker_iter=1
