[tams]
ntrajectories = 32
nsplititer = 5000
loglevel = "WARNING"

[trajectory]
end_time = 5.0
step_size = 0.01
# 6 sigma
targetscore = 4.24264068712

[model]
theta = 1.0 
epsilon = 0.50

[runner]
type = "asyncio"
nworker_init=1
nworker_iter=1
