[tams]
ntrajectories = 100
nsplititer = 5000
loglevel = "WARNING"

[trajectory]
end_time = 5.0
step_size = 0.01
# 8 sigma
targetscore = 5.65685424949

[model]
theta = 1.0 
epsilon = 0.50

[runner]
type = "asyncio"
nworker_init=4
nworker_iter=1
