name: test_and_examples

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"

jobs:

  test:
    name: Test on (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        python-version: ['3.12', '3.13']
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Python info
        shell: bash -e {0}
        run: |
          which python
          python --version
      - name: Install dependencies
        run: python -m pip install .[dev]
      - name: Run tests
        run: python -m pytest tests/

  doublewell:
    name: DoubleWell
    runs-on: 'ubuntu-latest'
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.12', '3.13']
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Python info
        shell: bash -e {0}
        run: |
          which python
          python --version
      - name: Install dependencies
        run: python -m pip install .[exec]
      - name: Run doublewell
        run: |
          cd examples/DoubleWell3D
          python doubleWell3D.py -i input_dw3D.toml

  boussinesq:
    name: Boussinesq_${{ matrix.python-version }}
    runs-on: 'ubuntu-latest'
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.12', '3.13']
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Python info
        shell: bash -e {0}
        run: |
          which python
          python --version
      - name: Install dependencies
        run: python -m pip install .[exec]
      - name: Run Boussinesq
        run: |
          cd examples/Boussinesq
          sed -i "s#epsilon = 0.01#epsilon = 0.05#g" input.toml
          python TAMS_2DBoussinesq.py
